# Generated by Django 4.1.7 on 2023-03-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('logdt', models.DateTimeField(blank=True, null=True)),
                ('event', models.CharField(blank=True, max_length=100, null=True)),
                ('difference', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
